# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClearingsExtractorDialog
                                 A QGIS plugin
 Extracts power line clearings boundaries from satellite imagery
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-03
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Yana Bakhramkhan
        email                : yana@qgis.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt import uic
from qgis.PyQt.QtWidgets import QDialog
import os

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'clearings_extractor_dialog_base.ui'))

class ClearingsExtractorDialog(QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(ClearingsExtractorDialog, self).__init__(parent)
        self.setupUi(self)